### PR TITLE
Add the base label in the to_comment method

### PR DESCRIPTION
**Pull request by vitogit**
This should add the info about to which branch we are doing the PR (if not it will be pretty close).

I couldn't do the full integration (live github and pivotal) because I didn´t have enough time. Could you test the integration?

### CODE REVIEW

**Comment by marnen** [comment]
Thanks for the pull request! It does need tests, and you're in the best position to write them. Please do so.

**Comment by marnen** [comment]
Actually, on second look, the tests you've written _may_ be sufficient. Does this break the existing tests.

**Comment by vitogit** [comment]
I added 1 more test, locally all tests run fine.  Travis is failing , not sure why (missing env vars?)

**Comment by marnen** [comment]
OK, I'm looking at this again. Tests pass locally, even though they don't on Travis, and from a code point of view, I'm willing to merge this. But why is this useful? That is, from a user's point of view, what is the reason for this feature?

**Comment by vitogit** [comment]
The new process for prs is first development and then release branch, this generated 2 gitbot comments  that are almost the same. 
What I did is useful because it add the info about the target branch, and it will say which PR goes to development and which goes to release branch. This way you can tell that those PRs are for different branches and also check if the pivotal issue has the same release label as the target branch.

**Comment by marnen** [comment]
> The new process for prs is first development and then release branch, this generated 2 gitbot comments that are almost the same.

I know, but the only time I've been seeing pull requests directly to release branches is in support issues, for which we don't use Pivotal Tracker anyway. :) Are we actually doing that on non-support projects?

**Comment by marnen** [comment]
Hmm. Actually...
I did intend this to be a generally useful tool, not just an RBM one (which is why this repo is public). So I think I will merge this, and probably add a config property to turn it off.

**Pull request merged**
